# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='updated_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
